TEST = "TEST"

# Database
DBDriver = "mysql"
DBUser = "tpp"
DBPass = "123"
DBHost="127.0.0.1"
DBPort="3306"
DBName = "dormapp"

# Redis
RedisHost = "127.0.0.1:6379"
RedisPassword = ""

# Server
SrvHost = "25.43.134.201"
SrvPort = "8080"